apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http-grafana
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: observability
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http-grafana
    nodePort: 30300
  selector:
    app: grafana