apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: observability
data:
  mimir.yaml: |
    # Disable multitenancy
    multitenancy_enabled: false
    
    # Configure server
    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      log_level: info
    
    activity_tracker:
      filepath: /data/mimir/metrics-activity.log
      
    # Common configuration
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data/mimir/blocks
          
    # Ingester configuration
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
        replication_factor: 1
        
    # Distributor configuration  
    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
          
    # Querier configuration
    querier:
      max_concurrent: 20
      
    # Store gateway configuration
    store_gateway:
      sharding_ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
          
    # Ruler configuration
    ruler:
      rule_path: /data/mimir/data-ruler/
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /data/mimir/ruler
    
    blocks_storage:
      backend: filesystem
      bucket_store:
        sync_dir: /data/mimir/tsdb-sync
      tsdb:
        dir: /data/mimir/tsdb

    compactor:
      data_dir: /data/mimir/data-compactor
    
    alertmanager:
      data_dir: /data/mimir/data-alertmanager
        
    # Limits configuration
    limits:
      ingestion_rate: 100000
      ingestion_burst_size: 200000
      max_global_series_per_user: 0
      max_global_series_per_metric: 0
      max_cache_freshness: 10m