apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: observability
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:2.10.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9095  
          name: grpc
        args:
        - -config.file=/etc/mimir/mimir.yaml
        - -target=all
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: data
          mountPath: /data/mimir
        env:
        - name: GOMEMLIMIT
          value: "1GiB"
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: data
        persistentVolumeClaim:
          claimName: mimir-data
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001