apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-data
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "hostpath"