apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: observability
  labels:
    app: mimir
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: grpc
  selector:
    app: mimir