apiVersion: v1
kind: Service
metadata:
  name: logging-app-service
  labels:
    app: logging-app
spec:
  type: ClusterIP
  selector:
    app: logging-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: logging-app-nodeport
  labels:
    app: logging-app
spec:
  type: NodePort
  selector:
    app: logging-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http