apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: logging-app
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"