apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: logging-app-production

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

namePrefix: prod-

commonLabels:
  env: production